<?php
$config['general_config_file_version'] = '1.0';





$config['project_name'] = 'handshake';

#################################################################################
# Date/Time Settings

//TODO: TO BE REMOVED
$config['date_format']				=	'd-m-Y';

// Date format used for displaying date in HTML from PHP default format (Y-m-d)
$config['date_display_format']		=	'd-M-Y';

// Date Time format used for displaying date in HTML from PHP default format (Y-m-d H:i:s)
$config['datetime_display_format']	=	'd-M-Y H:i:s';

//Date format used in Javascript libraries & functions (Eg: datepicker)
$config['js_date_format']			=	'dd-mm-yyyy';

//Date format used in Javascript libraries & functions (Eg: datepicker)
$config['js_datetime_format']		=	'dd-mm-yyyy hh:mm:ss';

//Date format of PHP that matches the javascript date format
$config['php_to_js_date_format']	=	'd-m-Y';

//Timezone Asia/Kuwait,Asia/Kolkata
$config['php_timezone']	=	'Asia/Kolkata';

//Customer import Time format
$config['csv_date_format']	=	'd-M-Y';

#################################################################################
# Email Settings

//	If set to true, email will be sent only to the address specified in _TESTING_EMAIL
$config['send_test_emails_only']	= true;

//	Email address for testing in Test servers. Mails can be addressed to this email during testing instead of customers address
$config['testing_email']	= "joby.joseph@codepoints.in";

//	Email address for use in 'From' address when specific mails are sent
$config['sender_address']	= "noreply@codepoints.in";//

//	Sender name for the mails are sent
$config['sender_name']	= "SQMS";

//	Administrator Email address to which error mails are sent
$config['admin_email']	= "sarath@codepoints.in";

//	Disclaimer to be appended at the end of the email
$config['email_disclaimer']	= 'This message is generated by the system. Do not reply to this message.';

//	http url of SQMS logo 
$config['email_sqms_log_url']	= _BASE_URL.'images/logo_sqms.png';

//	http url of Bank logo 
$config['email_bank_logo_url']	= _BASE_URL.'images/ahliunbank-logo_report.png';

//	Sender name for the mails are sent
$config['email_signature'] = "<br>Thank You,
			<br>Regards
			<br>Team SQMS";

//	Sender name for the mails are sent
$config['email_from_name'] = "Team SQMS";

#################################################################################
# SMS Settings

//	If set to true, sms will be sent to the phone number based on *send_test_sms_only*
$config['send_sms']	= false;

//	If set to true, sms will be sent only to the phone number specified in *testing_mobile*
$config['send_test_sms_only']	= true;

// mobile number for testing in Test servers. SMS can be addressed to this phone number during testing instead of customers phone number
$config['testing_mobile']	= "9447958235";

#################################################################################
# Other Settings

// Delimiter used to separate string values
$config['string_delimiter']	= '#??#';

// Error login attempt  limit
$config['consecutive_failed_login_count']	= 3;

// Max Idle Session time for user (In mins)
$config['max_idle_session_time']	= 5;

#################################################################################
// Default image file for items
$config['_DEFAULT_ITEM_IMAGE']		= 'images/default_thumbnail.jpg';

// Config Variable to determine if delivery order and delivery acknowledgement is added on service acceptance approval approved
$config['_DELIVERY_ACKNOWLEDGE_FOR_SERVICE']		= true;

// warning message form permission amount
$config['_AMOUNT_RANGE_WARNING_MSG']			=	'The amount you can add/approve is between';

//Password expiry in days
$config['_PASSWORD_EXPIRE_DAY']		=	30;

//Auto escalation hrs
$config['_AUTO_ESCALATION_HOURS']	=	24;

//Password expiry in days
$config['_ENABLE_ACCOUNT_LOGIN_POLICY']	=	true;

####################### DOCUMENT ASSESSMENT ####################################
//No. of days for calculating Expected response date
$config['_EXPECTED_RESPONSE_DAYS']	=	2;

//Document Database id prefix
$config['_DOCUMENT_DATABASE_CODE_PREFIX']	=	'DOC_';

//Assessment Types
$config['_CHECKLIST_ASSESSMENT_TYPES']	=	array("Document Checklist", "Audit Checklist", "Questionnaire");

//Document Review id prefix
$config['_DOCUMENT_REVIEW_CODE_PREFIX']	=	'DOCR_';

//Document review checklist type
$config['_DOCUMENT_REVIEW_CHECKLIST_TYPE']	=	'Document Assessment';

//Document review response date days
$config['_DOCUMENT_REVIEW_RESPONSE_DAYS']	=	2;

//Weekend Days
$config['_WEEKEND_DAYS']	=	array('Friday', 'Saturday');

//Date change reason
$config['_CHECKLIST_ANSWER_TYPES']	=	array("Polar", "Polar with fixed score", "Polar with custom score");

//Document review reminder days
$config['_DOCUMENT_REVIEW_REMINDER_DAYS']	=	6;

####################### INTERNAL/ONSITE AUDIT ####################################

//Onsite/Internal audit program id prefix
$config['_ONSITE_AUDIT_PROGRAM_ID_PREFIX']	=	'DOC_';

//Onsite/Internal audit program checklist type
$config['_ONSITE_AUDIT_PROGRAM_CHECKLIST_TYPE']	=	'Internal/Onsite Audit';

//Onsite/Internal audit program frequency
$config['_ONSITE_AUDIT_PROGRAM_FREQUENCY'] =    array(
													"Daily",
													"Weekly",
                                                    "Monthly",                                                                                                       
                                                    "Quarterly",
                                                    "Half yearly",
                                                    "Yearly"
                                                );

####################### RISK ASSESSMENT ####################################

//Risk matrix code prefix
$config['_RISK_MATRIX_CODE_PREFIX']	=	'RSK_';

//Impact/Probability rank limit
$config['_IMPACT_PROBABILITY_MAX_RANKING']	= 10;

####################### MYSTERY SHOPPER ####################################

//Document Database id prefix
$config['_MYSTER_SHOPER_PREFIX']	=	'MSP_';

$config['_MYSTER_SHOPER_ACC_PREFIX']	=	'MSPA_';

//Risk matrix code prefix
$config['_MS_PROGRAM_CODE_PREFIX']	=	'MSP_';

//Assessment Types
$config['_MS_PROGRAM_CHECKLIST_TYPE']	=	"MS Program";

//Date change reason
$config['_MS_DATECHANGE_REASON']	=	array("Unable to go");

// Maximum days to send the assessment details to bank staff
$config['_DAYS_SEND_TO_BANK_STAFF']	=	4;

// Maximum days to send the assessment details to bank staff
$config['_MAXDAYS_FOR_BANK_OBJECTION']	=	1;

####################### INTERNAL STAFF ASSESSMENT ############################

//Internal staff assessment program id prefix
$config['_INTERNAL_STAFF_ASSESSMENT_PROGRAM_ID_PREFIX']	=	'ISA_';

//Onsite/Internal audit program frequency
$config['_INTERNAL_STAFF_ASSESSMENT_PROGRAM_FREQUENCY'] =    array(
                                                    "No",
                                                    "Monthly", 
                                                    "Quarterly",
                                                    "Half yearly",
                                                    "Yearly"
                                                );

//Assessment Types
$config['_INTERNAL_STAFF_ASSESSMENT_CHECKLIST_TYPE']	=	"Internal Staff Assessment";

############################### CALL REVIEW ##################################

//Call review program id prefix
$config['_CALL_REVIEW_PROGRAM_ID_PREFIX']	=	'CALL_';

//Assessment Types
$config['_CALL_REVIEW_CHECKLIST_TYPE']	=	"Call Review";

############################### CAMERA REVIEW ##################################

//Camera review program id prefix
$config['_CAMERA_REVIEW_PROGRAM_ID_PREFIX']	=	'CAMERA_';


//Currency decimal places
$config['_CURRENCY_DECIMAL_PLACES']	=	3;

//Email footer
$config['_EMAIL_FOOTER']                =	'Ahli United Bank';

############################### Spark ##################################
//Survey schedule
$config['_SURVEY_FREQUENCY'] =    array(
                                                    "No",
                                                    "Daily", 
                                                    "Weekly",
                                                    "Monthly",
                                                    "Quarterly",
                                                    "Half yearly",
                                                    "Yearly"
                                                );

//Survey code prefix
$config['_SURVEY_CODE_PREFIX']	=	'ESS_';


// mystery shopper application login
$config['_MYSTERY_SHOPPER_LOGIN_URL']	=	'http://localhost:7020/aubk-sqms-online/';

####################### REPORTS ####################################
//CIF OPENED array
$config['_CIF_OPENED']			=    array("9113"=>"staff","5211"=>"retail","6111"=>"vip","5111"=>"premium","5312"=>"dsu","4321"=>"cbd");
$config['_PERCENTAGE_FORMAT']	=	2;
$config['_TIME_LAPSE_FORMAT']	=	2;


$config['_TYPE_OF_SETTLEMENT']	= array(
									"BuyOut",
									"Closed to Cash",
									"Closed to Legal"
									);

$config['_ATM_TAT_ISSUE_TYPES']	=	array("total instant issue","instant and delivered","instant and not delivered","total central issue","central issue for amil delivered","central issue for amil not delivered","central issue and delivered","central issue and not delivered");

// LG processing elapsed time constant
$config['_LG_PROCESSING_ELAPSE_CONST']		=	2;

// LG Amendment elapsed time constant
$config['_LG_AMENDMENT_ELAPSE_CONST']		=	2;

// LC processing elapsed time constant
$config['_LC_PROCESSING_ELAPSE_CONST']		=	4;

// LC Amendment elapsed time constant
$config['_LC_AMENDMENT_ELAPSE_CONST']		=	4;

// Bills processing elapsed time constant
$config['_BILLS_PROCESSING_ELAPSE_CONST']	=	4;

// BC processing elapsed time constant
$config['_BC_PROCESSING_ELAPSE_CONST']		=	4;

$config['_CARDS_CANCELLED_STATUS'] = array(
    1 => 'Personal Reason',
    3 => 'Better Deals & Offers',
    6 => 'Never Used the Card',
    7 => 'Do Not Like Credit Cards',
    9 => 'Has Multiple Cards',
    10 => 'Others'
);

// Static roles used in sqms
$config['_STATIC_ROLES'] = array(
    'SSUA',
    'SA',
    'NU'
);

############################### EXCEL IMPORT COMPAT SQ ##################################
//Compat SQ Branch code
$config['_BRANCH_CODE'] =    array(
										"1"=>'NBK',
										"2"=>'Boubyan',
										"3"=>'Gulf',
										"5"=>'KFH'
										
								);

//Compat SQ Process code
$config['_PROCESS_CODE']	=	array(
										"MG"=>'MG',
										"RO-PB"=>'RO-PB',
										"TR"=>'TR'
								);

//Compat SQ Criteria
$config['_CRITERIA_CODE']	=	array(
										"staff_image"					=>	'Staff Image',
										"serving_customer"				=>	'Serving the Customer',
										"KYC"							=>	'Customer protection Knowing customer needs KYC',
										"fairness_equality"				=>	'Customer protection Fairness and equality',
										"cross_sales_initiative"		=>	'Customer protection Cross Sales Initiative',
										"product_knowledge"				=>	'Customer protection Product Knowledge',
										"awareness_financial_education"	=>	'Customer protection Awareness and Financial Education',
										"confidentiality"				=>	'Confidentiality'
								);
//Compat MG Criteria max score
$config['_MG_MAX_SCORE']	=	array(
										"staff_image"					=>	20,
										"serving_customer"				=>	45,
										"fairness_equality"				=>	05,
										"product_knowledge"				=>	20,
										"confidentiality"				=>	10
								);
//Compat RO Criteria max score
$config['_RO_MAX_SCORE']	=	array(
										"staff_image"					=>	20,
										"serving_customer"				=>	45,
										"KYC"							=>	05,
										"fairness_equality"				=>	05,
										"cross_sales_initiative"		=>	15,
										"product_knowledge"				=>	20,
										"awareness_financial_education"	=>	07,
										"confidentiality"				=>	10
								);
####################### DYNAMIC REPORTS ####################################

//Risk matrix code prefix
$config['MENUTYPE_ID']	=	'11';

// Month RO view table re create flag
$config['VIEW_RECREATE']	=	TRUE;

####################### MENU TYPE SETTINGS ####################################

$config['MS_MENUTYPE_NAME']	=	'Mystery Shoppers';
$config['IS_MENUTYPE_NAME']	=	'Internal Staff Assessment';
$config['DA_MENUTYPE_NAME']	=	'Document Assessment';
$config['OA_MENUTYPE_NAME']	=	'Internal / Onsite Audit'; 




/*
 * Total days the bankstaff objection to be blocked from staff
 */
$config['BANK_STAFF_OBJECTION_WAITING_DAYS']	=	2; 

# [CONSTANT VAR] base url 
define("_SPARK_BASEPATH", "I2E");

# [CONSTANT VAR] base url 
define("_SPARK_TITLE", "I2E");

/*
 * menu permission array 
 * @title holds the title of menu
 * @icon holds path of icons
 * @visible tells whether to show or hide a menu in header 
 */
$config['SPARK_MENU_PERMISSION'] = array(
    'Dashboard' => array('SA' => "Yes", "All" => "Yes","title"=>"Dashboard","icon"=>"images/dashboard.png","visible"=>"Yes"),
    'AreaOfImpact' => array('SA' => "Yes", "All" => "No","title"=>"","icon"=>"","visible"=>"No"),
    'BannerImages' => array('SA' => "Yes", "All" => "No","title"=>"Banner Images","icon"=>"images/gallery.png","visible"=>"Yes"),
    'BenefitToBank' => array('SA' => "Yes", "All" => "No","title"=>"","icon"=>"","visible"=>"No"),
    'EmployeeFeedback' => array('SA' => "Yes", "All" => "Yes","title"=>"Suggestions","icon"=>"images/feedback.png","visible"=>"Yes"),
    'EmployeeFeedbackReview' => array('SA' => "Yes", "All" => "Yes","title"=>"","icon"=>"","visible"=>"No"),
    'MediaGallery' => array('SA' => "Yes", "All" => "Yes","title"=>"Media Gallery","icon"=>"images/media_gallery.png","visible"=>"Yes"),
    'EmployeeSatisfactionSurvey' => array('SA' => "Yes", "All" => "No","title"=>"Employee Survey","icon"=>"images/survey-icon.png","visible"=>"Yes"),
    'EmployeeSatisfactionSurveySubmission' => array('SA' => "Yes", "All" => "Yes","title"=>"Employee Survey Submission","icon"=>"images/survey.png","visible"=>"Yes"),
    'AnswerType' => array('SA' => "Yes", "All" => "No","title"=>"","icon"=>"","visible"=>"No"),
    'SurveyQuestions' => array('SA' => "Yes", "All" => "No","title"=>"","icon"=>"","visible"=>"No"),
    'FeedbackReport' => array('SA' => "Yes", "All" => "No","title"=>"Suggestions Report","icon"=>"images/report.png","visible"=>"Yes"),
    'SurveyReport' => array('SA' => "Yes", "All" => "No","title"=>"Employee Survey Report","icon"=>"images/report.png","visible"=>"Yes"),
    'Notifications' => array('SA' => "Yes", "All" => "Yes","title"=>"","icon"=>"","visible"=>"No")
); 

// application login
$config['_SCMS_LOGIN_URL']	=	'http://localhost:7020/sqms/';


// If set to true, application will work only in google chrome browser
$config['browser_check']	= false;

// If set to true, application will work only in google chrome browser
$config['browser_warning_show']	= true;

$config['default_albums'][0]['name']                =   'Profile Photos';
$config['default_albums'][0]['description']         =   '';
$config['default_albums'][1]['name']                =   'My Uploads';
$config['default_albums'][1]['description']         =   '';
